[22] Integrar chats 1-1 front y back
TMDAD-Chat/front pull request #4
Opened 2022-05-02 17:09 UTC by lAngelP

2022-05-02 19:13 UTC, FreddyMartinez requested changes

2022-05-02 19:13 UTC, FreddyMartinez commented on src/app/components/auth/login/login.component.ts
> +        }
creo que el método `registerUser` nos lo podemos llevar al servicio de autenticación, para separar por contexto, y dejar la lógica de registrar el usuario ahí mismo.

2022-05-02 19:13 UTC, FreddyMartinez commented on src/app/services/contact.service.ts
> +    }
en principio este servicio no se debe poder llamar sin una sesión activa, con lo cual debe existir el email, en caso de duda lo podemos mover dentro del módulo principal para que lo proteja el guard :wink:

2022-05-02 19:13 UTC, FreddyMartinez commented on src/app/components/main/main.component.ts
> +    }
por lo general no se recomienda dejar suscripciones anidadas, porque pude tener efectos indeseados. Se recomienda usar un switchMap o algún otro operador para aplanar suscripciones.

2022-05-02 19:13 UTC, FreddyMartinez commented on src/app/components/main/main.component.ts
> +    }
de hecho, podríamos hacer que el servicio de conversaciones directamente devuelva los datos de usuarios, en vez de ir por ellos uno por uno

2022-05-02 19:13 UTC, FreddyMartinez commented on src/app/services/http.service.ts
> +  constructor(private httpClient: HttpClient) { }
este servicio lo podemos separar por contexto  :thinking:

2022-05-02 19:15 UTC, FreddyMartinez commented on src/app/services/contact.service.ts
> +    }
ya vi que los `if` son por la interfaz de firebase, lo cambio para que siempre devuelva un observable

2022-05-03 06:16 UTC, lAngelP commented on src/app/services/contact.service.ts
> +      return this.httpClient.get<ConversationsDto>(
En principio se puso el HttpClient para evitar que el resto de la aplicación conociese nada acerca de los endpoints del gateway, por que si hay que tocar algo, mejor que esté en un sitio que desperdigado

2022-05-03 06:16 UTC, lAngelP commented on src/app/services/conversation.service.ts
> +    return this.http.post<any>(environment.gateway + environment.messageReceiveApi + "/user/" + encodeURI(to) + "/message", body);
Ídem al anterior

2022-05-03 06:16 UTC, lAngelP commented on src/app/services/conversation.service.ts
> +    return this.http.post<any>(environment.gateway + environment.messageReceiveApi + "/user/" + encodeURI(to) + "/file", formData);
Ídem al anterior

2022-05-03 06:16 UTC, lAngelP commented on src/app/services/http.service.ts
>    constructor(private httpClient: HttpClient) { }
La idea de todo este servicio es abstraer la comunicación con el backend, de ahí todos los métodos que se han creado.

2022-05-03 06:16 UTC, lAngelP commented on src/app/services/sse/message.sse.service.ts
> +      const eventSource = this.sseService.getEventSource(environment.gateway + environment.messagePushApi + '/user/' + uri);
Ídem al anterior

2022-05-03 06:42 UTC, FreddyMartinez commented on src/app/services/contact.service.ts
> +      return this.httpClient.get<ConversationsDto>(
el string del endpoint lo debemos tener en el archivo de constantes, por lo que si el endpoint cambia se modifica ahi, y para cada endpoint solo se tiene un servicio que lo consume, que se reutiliza entre componentes, de modo que los sigues teniendo centralizados si necesitas cambiar algo en la forma en que se consume

2022-05-08 07:56 UTC, FreddyMartinez approved these changes

2022-05-08 07:56 UTC, merged